bytravel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hotel/', include('hotel.urls', namespace = 'hotel')),
    url(r'^order/', include('order.urls')),
    url(r'^contact/', include('contacts.urls')),
    url(r'^en/', include('en.urls')),
    url(r'^', include('byTravel.urls')),
]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

en/urls.py
from django.conf.urls import url
from .views import *

app_name = 'hotel'
urlpatterns = [
    url(r'^hotel/winter/(?P<slug>[-_\w]+)$', WinterDetailView.as_view()),
    url(r'^hotel/winter/$', 'en.views.winter_list_en'),
    url(r'^hotel/summer/$', 'en.views.summer_list_en'),
    url(r'^transfer/$', 'en.views.transfer_en'),
    url(r'^about/$', 'en.views.about_en'),
    url(r'^$', 'en.views.index_en'),
]

hotel/urls.py
from django.conf.urls import url
from .views import *

app_name = 'hotel'
urlpatterns = [
    url(r'^winter/$', WinterListView.as_view(), name = 'winterList'),
    url(r'^winter/(?P<slug>[-_\w]+)', WinterDetailView.as_view(), name = 'detail'),
    url(r'^summer/', SummerListView.as_view(), name = 'summerList')
]

hotel/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models
from froala_editor.fields import FroalaField


# Create your models here.

class Category(models.Model):
    title = models.CharField(verbose_name = _('Title'), max_length = 255)
    text = models.TextField()
    image = models.ImageField(verbose_name = _('Image'), upload_to = 'uploads/category/')

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'hotel_category'
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class CategoryEn(models.Model):
    title = models.CharField(verbose_name = _('Title'), max_length = 255)
    text = models.TextField()
    image = models.ImageField(verbose_name = _('Image'), upload_to = 'uploads/category/')
    belongs_to = models.ForeignKey(Category)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Категории на английском"


class Hotel(models.Model):
    title = models.CharField(verbose_name = _('Title'), max_length = 255)
    title_english = models.CharField(verbose_name="Название отеля на английском", max_length=55)
    slug = models.SlugField(verbose_name = _('Url'))
    about = FroalaField(verbose_name = _('About'))
    about_en = FroalaField(verbose_name="Описание отеля на англиском")
    min_cost = models.IntegerField(verbose_name = _('Minimal cost'))
    cost = models.IntegerField(verbose_name = _('Cost'))
    category = models.ForeignKey(Category, verbose_name = _('Category'), on_delete = models.CASCADE)
    img = models.ImageField(verbose_name = _('Image'), upload_to = 'uploads/hotel')
    RESTS = (
        ('w', _('Winter')),
        ('s', _('Summer'))
    )
    rest = models.CharField(verbose_name = _('Type of rest'), max_length = 1, choices = RESTS)
    latitude = models.CharField(verbose_name="Широта", max_length=20)
    longitude = models.CharField(verbose_name="Долгота", max_length=20)
    related = models.ManyToManyField('self', blank=True, null=True)

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'hotel'
        verbose_name = _('Hotel')
        verbose_name_plural = _('Hotels')


class Image(models.Model):
    image = models.ImageField(verbose_name = _('Image'), upload_to = 'uploads/hotel/images')
    hotel = models.ForeignKey(Hotel, verbose_name="К какому отелю относится")

    def pic(self):
        if self.image:
            return '<img src="%s" width="70">' %self.image.url
        else:
            return '(none)'
    pic.short_description = _('Big Image')
    pic.allow_tags = True

    class Meta:
        db_table = 'hotel_images'


class Hull(models.Model):
    title = models.CharField(verbose_name = "Название корпуса", max_length = 255)
    hull_en_title = models.CharField(verbose_name="Название корпуса на английском", max_length=55)

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'hull'
        verbose_name = _('Hull')
        verbose_name_plural = "Корпусы"



class Hostel(models.Model):
    hull = models.ForeignKey(Hull, on_delete = models.CASCADE)
    title = models.CharField(verbose_name = _('Title'), max_length = 255)
    title_en = models.CharField(verbose_name="Название на английском", max_length=55, default=None)
    cost = models.CharField(verbose_name = _('Field for cost'), max_length = 255)
    cost_en = models.CharField(verbose_name=" Цена на английском", max_length=55, default=None)
    note = models.TextField(verbose_name="Заметки")
    note_en = models.TextField(verbose_name="Заметки на англиском", default=None)

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'hostel'


class Tab(models.Model):
    title = models.CharField(verbose_name = _('Title'), max_length = 255)
    title_en = models.CharField(verbose_name="Название на английском", max_length=55)
    hotel = models.ForeignKey(Hotel, on_delete = models.CASCADE)
    hostel = models.ManyToManyField(Hostel)

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'tab'
        verbose_name = _('Проживание')
        verbose_name_plural = "Проживание"

hotel/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from byTravel.views import IndexView
from .models import *
from byTravel.models import *
from navbar.models import Navbar
# Create your views here.
class WinterListView(IndexView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super(WinterListView, self).get_context_data(**kwargs)
        for item in self.object_list:
            item.hotels = Hotel.objects.all().filter(rest = 'w', category = item)
        context['gmeta'] = GlobalMeta.objects.filter(title="global")
        context['lmeta'] = GlobalMeta.objects.filter(title="winter")
        return context

    template_name = 'hotel/winter.html'

class WinterDetailView(DetailView):
    model = Hotel

    def get_context_data(self, **kwargs):
        context = super(WinterDetailView, self).get_context_data(**kwargs)
        context['images'] = Image.objects.all().filter(hotel = self.object)
        context['tabs'] = Tab.objects.all().filter(hotel = self.object)
        context['hulls'] = Hull.objects.all()
        context['navbars'] = Navbar.objects.all()
        for tab in context['tabs']:
            for hull in context['hulls']:
                hull.count = False
                for hostel in tab.hostel.all():
                    if hostel.hull.id == hull.id:
                        hull.count = True
        context['socials'] = Social.objects.all()
        context['addresses'] = Address.objects.all()
        context['phones'] = Phone.objects.all()
        context['mails'] = Mail.objects.all()
        context['gmeta'] = GlobalMeta.objects.filter(title="global")
        context['lmeta'] = LocalMeta.objects.filter(hotel=self.object)

        return context
    template_name = 'hotel/winter_detail.html'

class SummerListView(IndexView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super(SummerListView, self).get_context_data(**kwargs)
        for item in self.object_list:
            item.hotels = Hotel.objects.all().filter(rest = 's', category = item)
        context['gmeta'] = GlobalMeta.objects.filter(title="global")
        context['lmeta'] = GlobalMeta.objects.filter(title="summer")
        return context

    template_name = 'hotel/summer.html'

templates/hotel/summer.html
{% extends 'base.html' %}
{% block content %}
    <div class="summer">
	    <div class="container">
	    	<h2>ЛЕТНИЙ ОТДЫХ</h2>
	    </div>
    </div>
    <div class="price">
	<div class="container">
         {% for item in category_list %}
             {% if item.hotels %}
		        <div class="price-content">
		        	<div class="titlebar">
		        		<h3>{{ item.title }}</h3>
		        		<p>{{ item.text }}</p>
		        	</div>
		        	    <div class="bases">
		        	    	<ul>
                                {% for hotel in item.hotels %}
                                    {% if item.id == hotel.category.id %}
                                        <li>
			    	    	                <a href="{% url 'hotel:detail' hotel.slug%}">
			    	    	                <div class="img-wrapper">
			    	    	    	       	<img src="{{ hotel.img.url }}"  alt="">
			    	    	    	       </div>
			    	    	    	       	<p>{{ hotel.title }}</p>
			    	    	    	       	<h5>от<span>${{ hotel.min_cost }}</span></h5>
			    	    	    	       </a>
			    	    	            </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                </div>
             {% endif %}
        {% endfor %}
    </div>
    </div>
{% endblock %}

templates/hotel/summer_en.html
{% extends 'base_en.html' %}
{% block content %}
    <div class="summer">
	    <div class="container">
	    	<h2>SUMMER REST</h2>
	    </div>
    </div>
    <div class="price">
	    <div class="container">
             {% for item in category_list %}
                 {% for hotel in hotels %}
                     {% if hotel.category_id == item.id %}
	    	        <div class="price-content">
	    	        	<div class="titlebar">
	    	        		<h3>{{ item.title }}</h3>
	    	        		<p>{{ item.text }}</p>
	    	        	</div>
	    	        	    <div class="bases">
	    	        	    	<ul>
                                    {% for hotel in hotels %}
                                        {% if item.belongs_to_id == hotel.category_id %}
                                            <li>
	    		    	    	                <a href="/en{% url 'hotel:detail' hotel.slug%}">
	    		    	    	                <div class="img-wrapper">
	    		    	    	    	       	<img src="{{ hotel.img.url }}"  alt="">
	    		    	    	    	       </div>
	    		    	    	    	       	<p>{{ hotel.title_english }}</p>
	    		    	    	    	       	<h5>от<span>${{ hotel.min_cost }}</span></h5>
	    		    	    	    	       </a>
	    		    	    	            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                    </div>
                     {% endif %}
                     {% endfor %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/hotel/winter.html
{% extends 'base.html' %}
{% block content %}
    <div class="winter">
	    <div class="container">
	    	<h2>ЗИМНИЙ ОТДЫХ</h2>
	    </div>
    </div>
    <div class="price">
	    <div class="container">
             {% for item in category_list %}
                 {% if item.hotels %}
	    	        <div class="price-content">
	    	        	<div class="titlebar">
	    	        		<h3>{{ item.title }}</h3>
	    	        		<p>{{ item.text }}</p>
	    	        	</div>
	    	        	    <div class="bases">
	    	        	    	<ul>
                                    {% for hotel in item.hotels %}
                                        {% if item.id == hotel.category.id %}
                                            <li>
	    		    	    	                <a href="{% url 'hotel:detail' hotel.slug%}">
	    		    	    	                <div class="img-wrapper">
	    		    	    	    	       	<img src="{{ hotel.img.url }}"  alt="">
	    		    	    	    	       </div>
	    		    	    	    	       	<p>{{ hotel.title }}</p>
	    		    	    	    	       	<h5>от<span>${{ hotel.min_cost }}</span></h5>
	    		    	    	    	       </a>
	    		    	    	            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                    </div>
                 {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/hotel/winter_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    {% if hotel.rest == 'w' %}
    <div class="winter">
	    <div class="container">
	    	<h2>ЗИМНИЙ ОТДЫХ</h2>
	    </div>
    </div>
    {% else %}
    <div class="summer">
	    <div class="container">
	    	<h2>ЛЕТНИЙ ОТДЫХ</h2>
	    </div>
    </div>
    {% endif %}

<div class="price winter-page">
	<div class="container">
		<div class="winter-page-container">
			<div class="price-content winter-content">
				<div class="titlebar">
					<h3>Общая информация</h3>
				</div>
				<div class="bases-bases-2">
					<h2>{{ hotel.title }}</h2>
                    {{ hotel.about|safe }}
                    {% if images %}
					    <ul>
                            {% for image in images %}
					    	    <li>
					    	    	<div class="img-wrapper">
                                        <a href="{{ image.image.url }}" data-lightbox="roadtrip">
                                            <img src="{{ image.image.url }}"  alt="">
                                        </a>
					    	    	</div>
					    	    </li>
                            {% endfor %}
					    </ul>
                    {% endif %}
				</div>
			</div>
            <div class="price-content winter-content">
				<div class="titlebar">
					<h3>Проживание</h3>
				</div>
					<div class="bases-bases-2">
						<h2>Размещение в отеле {{ hotel.title }}</h2>
						<p>Выберите и нажмите на интересующий Вас период проживания на базе. Стоимость откроется ниже.</p>
                        {% if tabs %}
                            {% for tab in tabs %}
						        <div class="tab-block">
						        	<a href="#" class="clickme">{{ tab.title }}</a>
                                    {% if tab.hostel %}
						        	    <div class="box">
						        	    	<h3>Гостиницы</h3>
						        	    	<table>
						        	    		<tr><th>Наименование услуги</th><th>Стоимость</th><th>Примечание</th></tr>
                                                {% for hull in hulls %}
                                                    {% if hull.count %}
                                                        <td>{{ hull.title }}</td>
                                                    {% endif %}
                                                    {% for hostel in tab.hostel.all %}
                                                        {% if hostel.hull.id == hull.id %}
                                                            <tr><td>{{ hostel.title }}</td><td>{{ hostel.cost }}</td><td>{{ hostel.note }}</td></tr>
                                                        {% endif %}
                                                    {% endfor %}
                                                {% endfor %}
						        	    	</table>
						        	    </div>
                                    {% endif %}
						        </div>
                            {% endfor %}
                        {% endif %}

				</div>
			</div>
            <div class="price-content winter-content">
				<div class="bases-bases-2">
                    <a class="red" id="trigger-modal" href="#"><p>Забронировать</p></a>
					 <a class="blue" href="#"><p>Цены на доп.услуги</p></a>
					 </div>
			</div>
        
			<div class="price-content winter-content">
				<div class="titlebar">
					<h3>Местоположение</h3>
				</div>
				<div class="bases-bases-2">
					 <div id="googleMap" style="width:760px;height:480px;"></div>

					 </div>
			</div>

		</div>
		<div class="sidebar">
            {% if hotel.related %}
			    <h3>Ближайшие отели</h3>
			    <ul>
                    {% for related in hotel.related.all %}
			    	    <li>
                            <a href="{%  url 'hotel:detail' related.slug%}"></a>
			    	    	<div class="img-wrapper">
			    	    		<img src="{{ related.img.url }}"  alt="">
			    	    	</div>
			    	    	<p>{{ related.title }}</p>
			    	    </li>
                    {% endfor %}
			    </ul>
            {% endif %}
		</div>
	</div>
</div>
<!-- Modal -->
<div class="modal-body" id="screen">
	<div id="modal">
	 <button></button>
	    <h3>Горнолыжная база Каракол</h3>
	    <p>Дорогие Друзья! Для того чтобы Ваша заявка была оформлена быстро и точно, большая просьба заполнить форму бронирования с верным указанием Ваших данных электронной почты и номеров телефона. Благодарим Вас за выбор нашего туристического агентства!</p>
        <form action="" method='POST'>{% csrf_token %}
	    <input type="text" class="texts" name ='name' placeholder="Фамилия. Имя. Отчество.*"/>
	    <input type="text" class="texts" name="email" placeholder="e-mail adress*"/>
	    <input type="text" class="texts" name="phone" placeholder="Контактный телефон*"/>
	    <input type="text" class="texts" name="deal" placeholder="Количество гостей*"/>
	    <span class="datePicker">Дата с:</span><input id="datepicker" name="from"><span class="Picker">По:</span><input  id="datepicker1" name="to">
	    <span class="select">Выбор комнаты:</span>
	    <select name="room">
            {% for tab in tabs %}
                {% for hostel in tab.hostel.all %}
                    <option name="{{ hostel.title }}">{{ hostel.title }}</option>
                {% endfor %}
            {% endfor %}
{#		   <option>2-х этажный коттедж</option>#}
{#		   <option>1-х этажный коттедж</option>#}
{#		   <option>3-х этажный коттедж</option>#}
{#		   <option>4-х этажный коттедж</option>#}
{#		   <option>5-х этажный коттедж</option>#}
		</select>
	    <textarea name="info" placeholder="Дополнительная информация:" rows="4" ></textarea>
	    <a type="submit" class="popup1" id="submit" href="">Забронировать</a>
            </form>
	</div><!-- end modal -->

</div><!--end madal-body  -->

{#    <form>#}
{#                        {% csrf_token %}#}
{#                        <input type="text" name = 'name'><br/>#}
{#                        <input type="email" name="email"><br/>#}
{#                        <input type="text" name="phone" id=""><br/>#}
{#                        <input type="number" name="deal"><br/>#}
{#                        <input type="number" name="from">#}
{#                        <input type="number" name="to"><br/>#}
{#                        <select name="room">#}
{#                            {% for tab in tabs %}#}
{#                                {% for hostel in tab.hostel.all %}#}
{#                                    <option name="{{ hostel.title }}">{{ hostel.title }}</option>#}
{#                                {% endfor %}#}
{#                            {% endfor %}#}
{#                        </select><br/>#}
{#                        <textarea name="info" id="" cols="30" rows="10"></textarea>#}
{#    </form>#}


    <!-- Скрипты подключай не в хедере а в самом внизу body Мура ("Иса") -->
{#<script>#}
{#    $(function(){#}
{#        $('#submit').click(function(e){#}
{#            e.preventDefault();#}
{#            $.ajax({#}
{#                data: $('form').serialize(),#}
{#                url: '/order/save/',#}
{#                method: 'post',#}
{#                success: function(res){#}
{#                    alert(res)#}
{#                }#}
{#            })#}
{#        })#}
{#    });#}
{##}
{##}
{#</script>#}




{% endblock %}

templates/hotel/winter_detail_en.html
{% extends 'base_en.html' %}
{% load staticfiles %}
{% block content %}
    {% if hotel.rest == 'w' %}
    <div class="winter">
	    <div class="container">
	    	<h2>WINTER REST</h2>
	    </div>
    </div>
    {% else %}
    <div class="summer">
	    <div class="container">
	    	<h2>SUMMER REST</h2>
	    </div>
    </div>
    {% endif %}

<div class="price winter-page">
	<div class="container">
		<div class="winter-page-container">
			<div class="price-content winter-content">
				<div class="titlebar">
					<h3>General Information</h3>
				</div>
				<div class="bases-bases-2">
					<h2>{{ hotel.title_english }}</h2>
                    {{ hotel.about_en|safe }}
                    {% if images %}
					    <ul>
                            {% for image in images %}
					    	    <li>
					    	    	<div class="img-wrapper">
                                        <a href="{{ image.image.url }}" data-lightbox="roadtrip">
                                            <img src="{{ image.image.url }}"  alt="">
                                        </a>
					    	    	</div>
					    	    </li>
                            {% endfor %}
					    </ul>
                    {% endif %}
				</div>
			</div>
            <div class="price-content winter-content">
				<div class="titlebar">
					<h3>Living</h3>
				</div>
					<div class="bases-bases-2">
						<h2>Accomodation in {{ hotel.title_english }}</h2>
						<p>Select your interested time. Prices will open below.</p>
                        {% if tabs %}
                            {% for tab in tabs %}
						        <div class="tab-block">
						        	<a href="#" class="clickme">{{ tab.title_en }}</a>
                                    {% if tab.hostel %}
						        	    <div class="box">
						        	    	<h3>Hotels</h3>
						        	    	<table>
						        	    		<tr><th>Service name</th><th>Price</th><th>Note</th></tr>
                                                {% for hull in hulls %}
                                                    {% if hull.count %}
                                                        <td>{{ hull.hull_en_title }}</td>
                                                    {% endif %}
                                                    {% for hostel in tab.hostel.all %}
                                                        {% if hostel.hull.id == hull.id %}
                                                            <tr><td>{{ hostel.title_en }}</td><td>{{ hostel.cost_en }}</td><td>{{ hostel.note_en }}</td></tr>
                                                        {% endif %}
                                                    {% endfor %}
                                                {% endfor %}
						        	    	</table>
						        	    </div>
                                    {% endif %}
						        </div>
                            {% endfor %}
                        {% endif %}

				</div>
			</div>
            <div class="price-content winter-content">
				<div class="bases-bases-2">
                    <a class="red" id="trigger-modal" href="#"><p>Make reservation</p></a>
					 <a class="blue" href="#"><p>Prices for additional services</p></a>
					 </div>
			</div>

			<div class="price-content winter-content">
				<div class="titlebar">
					<h3>Location</h3>
				</div>
				<div class="bases-bases-2">
					 <div id="googleMap" style="width:760px;height:480px;"></div>

					 </div>
			</div>

		</div>
		<div class="sidebar">
            {% if hotel.related %}
			    <h3>Neighbor hotels</h3>
			    <ul>
                    {% for related in hotel.related.all %}
			    	    <li>
                            <a href="/en{%  url 'hotel:detail' related.slug%}"></a>
			    	    	<div class="img-wrapper">
			    	    		<img src="{{ related.img.url }}"  alt="">
			    	    	</div>
			    	    	<p>{{ related.title_english }}</p>
			    	    </li>
                    {% endfor %}
			    </ul>
            {% endif %}
		</div>
	</div>
</div>
<!-- Modal -->
<div class="modal-body" id="screen">
	<div id="modal">
	 <button></button>
	    <h3>{{ hotel.title_english }}</h3>
	    <p>Dear frends! To avoid any problem with reservation, please fill this form correctly.</p>
        <form action="" method='POST'>{% csrf_token %}
	    <input type="text" class="texts" name ='name' placeholder="Name*"/>
	    <input type="text" class="texts" name="email" placeholder="Email*"/>
	    <input type="text" class="texts" name="phone" placeholder="Phone number*"/>
	    <input type="text" class="texts" name="deal" placeholder="How many guests*"/>
	    <span class="datePicker">From:</span><input id="datepicker" name="from"><span class="Picker">To:</span><input  id="datepicker1" name="to">
	    <span class="select">Choose room:</span>
	    <select name="room">
            {% for tab in tabs %}
                {% for hostel in tab.hostel.all %}
                    <option name="{{ hostel.title_en }}">{{ hostel.title_en }}</option>
                {% endfor %}
            {% endfor %}
{#		   <option>2-х этажный коттедж</option>#}
{#		   <option>1-х этажный коттедж</option>#}
{#		   <option>3-х этажный коттедж</option>#}
{#		   <option>4-х этажный коттедж</option>#}
{#		   <option>5-х этажный коттедж</option>#}
		</select>
	    <textarea name="info" placeholder="Edditional information:" rows="4" ></textarea>
	    <a type="submit" class="popup1" id="submit" href="">Make a reservation</a>
            </form>
	</div><!-- end modal -->

</div><!--end madal-body  -->

{#    <form>#}
{#                        {% csrf_token %}#}
{#                        <input type="text" name = 'name'><br/>#}
{#                        <input type="email" name="email"><br/>#}
{#                        <input type="text" name="phone" id=""><br/>#}
{#                        <input type="number" name="deal"><br/>#}
{#                        <input type="number" name="from">#}
{#                        <input type="number" name="to"><br/>#}
{#                        <select name="room">#}
{#                            {% for tab in tabs %}#}
{#                                {% for hostel in tab.hostel.all %}#}
{#                                    <option name="{{ hostel.title }}">{{ hostel.title }}</option>#}
{#                                {% endfor %}#}
{#                            {% endfor %}#}
{#                        </select><br/>#}
{#                        <textarea name="info" id="" cols="30" rows="10"></textarea>#}
{#    </form>#}


    <!-- Скрипты подключай не в хедере а в самом внизу body Мура ("Иса") -->
{#<script>#}
{#    $(function(){#}
{#        $('#submit').click(function(e){#}
{#            e.preventDefault();#}
{#            $.ajax({#}
{#                data: $('form').serialize(),#}
{#                url: '/order/save/',#}
{#                method: 'post',#}
{#                success: function(res){#}
{#                    alert(res)#}
{#                }#}
{#            })#}
{#        })#}
{#    });#}
{##}
{##}
{#</script>#}




{% endblock %}

templates/hotel/winter_en.html
{% extends 'base_en.html' %}
{% block content %}
    <div class="winter">
	    <div class="container">
	    	<h2>WINTER REST</h2>
	    </div>
    </div>
    <div class="price">
	    <div class="container">
             {% for item in category_list %}
                 {% for hotel in hotels %}
                     {% if hotel.category_id == item.id %}
	    	        <div class="price-content">
	    	        	<div class="titlebar">
	    	        		<h3>{{ item.title }}</h3>
	    	        		<p>{{ item.text }}</p>
	    	        	</div>
	    	        	    <div class="bases">
	    	        	    	<ul>
                                    {% for hotel in hotels %}
                                        {% if item.belongs_to_id == hotel.category_id %}
                                            <li>
	    		    	    	                <a href="/en{% url 'hotel:detail' hotel.slug%}">
	    		    	    	                <div class="img-wrapper">
	    		    	    	    	       	<img src="{{ hotel.img.url }}"  alt="">
	    		    	    	    	       </div>
	    		    	    	    	       	<p>{{ hotel.title_english }}</p>
	    		    	    	    	       	<h5>от<span>${{ hotel.min_cost }}</span></h5>
	    		    	    	    	       </a>
	    		    	    	            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                    </div>
                     {% endif %}
                     {% endfor %}
            {% endfor %}
        </div>
    </div>
{% endblock %}